export interface DomainEntry {
  domain: string
  provider: string
}

export const EMAIL_DOMAINS: DomainEntry[] = [
  { domain: 'gmail.com', provider: 'Gmail' },
  { domain: 'outlook.com', provider: 'Outlook' },
  { domain: 'yahoo.com', provider: 'Yahoo' },
  { domain: 'icloud.com', provider: 'iCloud' },
  { domain: 'hotmail.com', provider: 'Hotmail' },
  { domain: 'live.com', provider: 'Live' },
  { domain: 'proton.me', provider: 'Proton' },
  { domain: 'protonmail.com', provider: 'ProtonMail' },
  { domain: 'zoho.com', provider: 'Zoho' },
  { domain: 'aol.com', provider: 'AOL' },
  { domain: 'gmx.com', provider: 'GMX' },
  { domain: 'yandex.com', provider: 'Yandex' },
  { domain: 'fastmail.com', provider: 'FastMail' },
  { domain: 'tutanota.com', provider: 'Tutanota' },
  { domain: 'hey.com', provider: 'HEY' },
  { domain: 'mail.com', provider: 'Mail.com' },
  { domain: 'yahoo.co.uk', provider: 'Yahoo UK' },
  { domain: 'yahoo.co.in', provider: 'Yahoo India' },
]

export const DOMAIN_TYPOS: Record<string, string> = {
  'gamil.com': 'gmail.com',
  'gmial.com': 'gmail.com',
  'gmil.com': 'gmail.com',
  'gmal.com': 'gmail.com',
  'gmai.com': 'gmail.com',
  'gmali.com': 'gmail.com',
  'gnail.com': 'gmail.com',
  'gmaill.com': 'gmail.com',
  'gmmail.com': 'gmail.com',
  'gmaik.com': 'gmail.com',
  'gmak.com': 'gmail.com',
  'gmaul.com': 'gmail.com',
  'gmaio.com': 'gmail.com',
  'yahho.com': 'yahoo.com',
  'yaho.com': 'yahoo.com',
  'yahooo.com': 'yahoo.com',
  'yhoo.com': 'yahoo.com',
  'yhaoo.com': 'yahoo.com',
  'ayhoo.com': 'yahoo.com',
  'hotnail.com': 'hotmail.com',
  'hotmai.com': 'hotmail.com',
  'hotmil.com': 'hotmail.com',
  'hotmal.com': 'hotmail.com',
  'hotmial.com': 'hotmail.com',
  'outlok.com': 'outlook.com',
  'outllok.com': 'outlook.com',
  'outlokk.com': 'outlook.com',
  'outlock.com': 'outlook.com',
  'otulook.com': 'outlook.com',
  'outloo.com': 'outlook.com',
  'icloud.co': 'icloud.com',
  'iclud.com': 'icloud.com',
  'icoud.com': 'icloud.com',
  'aol.coom': 'aol.com',
  'aol.cmo': 'aol.com',
  'protonmai.com': 'protonmail.com',
  'protonmaill.com': 'protonmail.com',
}
